# Generated by Django 5.1.5 on 2025-04-28 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('date_joined', models.DateField(verbose_name='Дата приема на работу')),
            ],
        ),
        migrations.CreateModel(
            name='TabRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Отработанные часы')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab_app.employee', verbose_name='Сотрудник')),
            ],
        ),
    ]
