# Generated by Django 5.0.7 on 2025-05-01 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab_app', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabel',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab_app.employee'),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tabel',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
